### ISSUE TITLE
installDB.js does not belong as a separate command

### ISSUE THREAD

**Issue by fguitton** [dsi-icl/optimise-core#38]
This should be handled directly by your "beforeAll" Jest testing rules.

**Comment by fguitton** [comment]
On top of this, the DB does not stand across testing requiring manual deletion of the DB files every run, this is not efficient

**Comment by Radiateurs** [comment]
[UPDATE] the manual deletion if fixed in commit 021e67bb9ff1e473d05e88f51622ae5f1a7bb9fa

**Comment by Radiateurs** [comment]
[Issue update] It seems we might be blocked because of sqlite3. Since it's impossible to erase the database entirely with knex (without query) the easy way is to unlink() the database file but meanwhile it's deleted, jest already launched the next test and it fails because we have a EBUSY error (trying to access the database from multiple process).

**Comment by sou-c** [comment]
not sure if i am right. but we should remove the line 'node installDB.js' from travis.yaml and put a param in jest config that install the DB. so when travis starts the tests all the DBs are created in their separate node env. i will look into this

**Comment by sou-c** [comment]
http://jestjs.io/docs/en/setup-teardown.html

**Comment by Radiateurs** [comment]
I was using this before all test to setup the database and at the end remove everything.
This actually raise the EBUSY error.
